In [1]:
import tensorflow as tf

In [3]:
tf.__version__

'2.0.0'

# Constant

In [4]:
tensor = tf.constant([[23,43],[62,26]])

In [5]:
print(tensor)

tf.Tensor(
[[23 43]
 [62 26]], shape=(2, 2), dtype=int32)


In [10]:
tensor.shape

TensorShape([2, 2])

In [12]:
# will give only the value of the variable, without the session
tensor.numpy()

array([[23, 43],
       [62, 26]], dtype=int32)

# Variables

In [13]:
tf_variables = tf.Variable([[1., 2., 3.],[4., 5., 6.]])

In [14]:
print(tf_variables)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>


In [15]:
tf_variables.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

# Changing value in variables

In [19]:
tf_variables[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

# Operations with Tensors

In [20]:
tensors = tf.constant([[1, 2], [3, 4]])

In [22]:
tensors + 2

<tf.Tensor: id=43, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [23]:
tensors * 2

<tf.Tensor: id=45, shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

# String

In [24]:
tf_string = tf.constant("TensorFlow")

In [25]:
tf_string

<tf.Tensor: id=46, shape=(), dtype=string, numpy=b'TensorFlow'>

In [28]:
tf.strings.length(tf_string)

<tf.Tensor: id=47, shape=(), dtype=int32, numpy=10>

In [29]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=51, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

# Sorting array of strings

In [30]:
tf_s = tf.constant(["Tensorflow", "machine learning", "Deep learning"])

In [32]:
for string in tf_s:
    print(string)

tf.Tensor(b'Tensorflow', shape=(), dtype=string)
tf.Tensor(b'machine learning', shape=(), dtype=string)
tf.Tensor(b'Deep learning', shape=(), dtype=string)
